site_name: Gurple &mdash; GenAI Security for Purple Teams
theme:
  name: material
  logo: assets/logo_light.jpeg
  favicon: assets/favicon.png
  features:
    - navigation.path
    - navigation.instant
    - navigation.instant.prefetch
    - navigation.instant.progress
    - navigation.sections
    - navigation.indexes
    - navigation.tracking
    - content.code.annotate
    - toc.follow
    - navigation.footer
    - navigation.top
    - content.code.copy
    - content.tabs.link
  palette:
    # Default to Dark Mode
    - scheme: astral-dark
      primary: custom
      accent: custom
      toggle:
        icon: material/brightness-4
        name: Switch to light mode

    # Toggle to Light Mode
    - scheme: astral-light
      primary: custom
      accent: custom
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
  custom_dir: docs/.overrides
repo_url: https://github.com/felipepenha/gurple
repo_name: gurple
site_author: Felipe Campos Penha
site_url: https://felipepenha.github.io/gurple/
site_dir: site
site_description: Documentation for Gurple.
copyright: >
  Copyright &copy; 2025 Felipe Campos Penha.
  Licensed under <a href="https://creativecommons.org/licenses/by-nc-nd/4.0/" target="_blank" rel="license noopener">CC BY-NC-ND 4.0</a>.
markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.snippets:
  - pymdownx.magiclink:
  - attr_list:
  - toc:
      anchorlink: true
      anchorlink_class: "toclink"
  - md_in_html:
  - pymdownx.inlinehilite:
  - pymdownx.superfences:
  - markdown.extensions.attr_list:
  - pymdownx.keys:
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.tabbed:
      alternate_style: true
plugins:
  - search
# git-revision-date-localized removed
# redirects removed

extra_css:
  - stylesheets/extra.css
extra_javascript:
  - js/extra.js
extra:
  analytics:
    provider: fathom
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/felipepenha/gurple
  version: 0.0.1
nav:
  # - Template Examples: template_examples.md
  # - Major Section Example:
  #     - major_section_example/index.md
  #     - First Page: major_section_example/page_1.md
  - Home: index.md
  - About the Author:
      - author/index.md
  - Preface:
      - preface/index.md
  - Introduction:
      - introduction/index.md
  - Threat, Vulnerability & Risk Frameworks:
    - threat_vulnerability_frameworks/index.md
    - C|P-RMM: threat_vulnerability_frameworks/cp_rmm.md
    # - MITRE ATLAS: threat_vulnerability_frameworks/mitre_atlas.md
    # - OWASP Top 10: threat_vulnerability_frameworks/owasp_top_10.md
    # - OWASP Top 10 for LLM: threat_vulnerability_frameworks/owasp_top_10_llm.md
    # - OWASP Top 10 for Agentic: threat_vulnerability_frameworks/owasp_top_10_agentic.md
    # - Taxonomy of Prompt Injection: threat_vulnerability_frameworks/taxonomy_prompt_injection.md
  - Attack Entry Points:
      - attack_entry_points/index.md
  - Threats:
    - threats/index.md
    - G-1.1 Jailbreaking:
      - threats/jailbreaking/index.md
      - G-1.1.1 Optimized Jailbreaking: threats/jailbreaking/optimized.md
    # - Prompt Injection:
    #   - threats/prompt_injection/index.md
    # - Exfiltration:
    #   - threats/exfiltration/index.md
    # - Poisoning:
    #   - threats/poisoning/index.md
    # - Unbounded Consumption:
    #   - threats/unbounded_consumption/index.md
    # - Supply Chain Exploitation:
    #   - threats/supply_chain_exploitation/index.md
    # - Model Replication:
    #   - threats/model_replication/index.md
    # - Model Inversion:
    #   - threats/model_inversion/index.md
    # - Model Tampering:
    #   - threats/model_tampering/index.md

